services:
  api-server:
    build:
      context: .
    container_name: api-server
    volumes:
      - ./:/api-server/
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: bash -c "sleep 5 && 
           migrate -path ./migrations -database 'postgres://postgres:123456@postgres:5432/people_db?sslmode=disable' up &&
           go run cmd/main.go"

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  pg_data: {}
